### PR TITLE
Max Intel Lines

### PR DESCRIPTION
**Pull request by Raykazi**

### CODE REVIEW

**Comment by Paic** [comment]
I like the idea of setting a max number of line for the intel collection, it prevent it from getting too big and laggy.

What about directly removing the last item in the ObservableCollection in `IntelDataList_CollectionChanged` if a new one is added ? I think that would avoid some mental gymnastic with a flag being set and used in a background thread. Would it be to costly in performance ?

**Comment by Slazanger** [comment]
I think limiting by time is more useful.. like the zkb feed

**Comment by Paic** [comment]
When you're saying by time you mean like "keep only the intel that is less than 2 hours old" ? Indeed if it is that it is better to do it the way the PR is already coded, that would limit the number of time the collection has to be iterated.

**Comment by Slazanger** [comment]
basically yes, although I was thinking a default that matched the zkill feed

**Comment by Slazanger** [comment]
This ended up implemented as part of an additional optimisation

**Pull request closed without merging**
